{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keel.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "keel.name" . }}
    helm.sh/chart: {{ include "keel.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: 9300
      protocol: TCP
      name: keel
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  sessionAffinity: None
{{- end }}
